server:
  port: 8080

spring:
  application:
    name: concert-reservation
  #  mysql
#  datasource:
#    url: jdbc:mysql://localhost:3306/hh_concert
#    username: whee
#    password: whee
#    driver-class-name: com.mysql.cj.jdbc.Driver
  #  h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:concert
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
