spring:
  application:
    name: concert-reservation
  datasource:
    url: jdbc:mysql://localhost:3306/hh_concert
    username: whee
    password: whee
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  h2
  #  datasource:
  #  url: jdbc:h2:tcp://localhost/~/hanghae;MVCC=TRUE
  #  username: sa
  #  password:
  #  driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
